### ISSUE TITLE
Temperature Feedback Issue

### ISSUE THREAD

**Issue by ellmotion** [bird-sanctuary/bluejay#163]
### Describe the issue

Hello,
I am unable to get the temperature feedback from my ESCs in Betaflight. The temperature remains at 0.
I have properly enabled DShot EDT.
ESC: SpeedyBee BLS 50A
FC: SpeedyBee F405 V3
![image1](https://github.com/bird-sanctuary/bluejay/assets/1707394/6fd37ff5-f15f-4a1b-b4f1-8081614737e6)
![image3](https://github.com/bird-sanctuary/bluejay/assets/1707394/27648b86-8242-4052-b8eb-aae7c745deb8)
![image2](https://github.com/bird-sanctuary/bluejay/assets/1707394/79c3d7d2-fd42-44f0-a7ac-3a4a8aaeaacc)
[BTFL_cli_20230818_132422_SPEEDYBEEF405V3.txt](https://github.com/bird-sanctuary/bluejay/files/12378757/BTFL_cli_20230818_132422_SPEEDYBEEF405V3.txt)

### Bluejay version

0.20

### ESC variant

J_H_50

### PWM frequency

24

### DShot bitrate

300

### Bidirectional DShot

On

### FC firmware

Betaflight 4.4.2

**Comment by damosvil** [comment]
Please, try Betaflight 4.4.0. In Betaflight 4.4.2 It seems that shot
commands doesn't work fine

**Comment by ellmotion** [comment]
You are right, I have flash BF in 4.4.0 and I have the temperature feedback.
Thanks
![image](https://github.com/bird-sanctuary/bluejay/assets/1707394/276bb83d-687d-45de-8683-db8448cc3bea)
