### ISSUE TITLE
please preserve 96khz pwm mode

### ISSUE THREAD

**Issue by jli** [bird-sanctuary/bluejay#168]
In the release notes of 0.20.0, I noticed this:
> In process of experimenting with dynamic PWM we came to the conclusion that 96kHz mode is pretty much useless and we might get rid of it in the future. The resolution on 96kHz is 256 steps in the best case. Considering deadtime, (which needs to be subtracted) - having high dead times reduces this even further.

I fly tiny whoops and use 96khz on most of my builds for increased flight time. This is especially important for my heavier HD whoops. I know many/most people recommend against 96khz because of worse flight characteristics, but to be honest I haven't noticed, and I value the flight time benefits.

I have not done careful side by side testing to measure flight time differences, but anecdotally I think it increases light freestyle flight times on my 65mm builds from ~3:09 to ~3:20 with 300mah, and on 75mm from ~4:30 to ~5:15. I can do more careful tests if that would be valuable.

Thanks!

**Comment by damosvil** [comment]
96khz mode will be present in 0.20.1 when it is avaliable, and in future releases:
https://github.com/bird-sanctuary/bluejay/pull/154
