### ISSUE TITLE
Dshot600 not available

### ISSUE THREAD

**Issue by mankeli** [bird-sanctuary/bluejay#169]
### Describe the issue

Hi! Not a bug report, but a question: I'm trying to use BlueJay with Emax Bullet 30A esc's. I'm trying to set Dshot600 as protocol from betaflight, but after saving the settings it always reverts back to Dshot300. While this is probably not a problem in practice, I'm wondering what might cause it to downgrade? Does bluejay measure esc cpu speed, or does Betaflight test which bitrate is reliable for communication?

### Bluejay version

0.19.2

### ESC variant

M-H-30

### PWM frequency

48

### DShot bitrate

Any

### Bidirectional DShot

On

### FC firmware

Betaflight 4.2.2

### Motor size

2205

**Comment by stylesuxx** [comment]
Bluejay does not downgrade your BF settings. Most likely your FC or your PID loop settings do not allow dshot600 (or do not make sense). If you share your BF settings and FC we probably could tell you more.

**Comment by stylesuxx** [comment]
@mankeli - any update on this, otherwise I will close this issue.

**Comment by TheRedGamerFPV** [comment]
I have the same issue that @mankeli has, betaflight likes to spit an error when I select any of the Dshot protocols, I'm using a DYS f4 v2 flight controller, which is listed as being Dshot600 compatable, and I am using lumenier 30A opto 3-6s BLHeli_s DHSOT ESC's, the only protocol that seems to work is multishot, the esc's are dshot, oneshot, multishot and PWM compatable, yet selecting any dshot, and then saving and reboot results in the errors in the images, I'd be happy to provide logs or more information if you'd like
![image](https://github.com/bird-sanctuary/bluejay/assets/49452378/8399082e-2df9-401b-a5c7-bace7ed83625)
![image](https://github.com/bird-sanctuary/bluejay/assets/49452378/f1e8b750-adf6-48ca-88b6-34958f71b9c3)

**Comment by damosvil** [comment]
Please could you read the esc firmware versión is installed in your escs using esc-configurator.com tool?

**Comment by damosvil** [comment]
Also to outline that your FC has a f405 mcu. In the latest versions of Betaflight your mcu is no longer capable of running a 8k pid loops, so Betaflight won't allow you to choose that pid loop neither dshot 600 protocol

**Comment by hyp0dermik-code** [comment]
> I have the same issue that @mankeli has, betaflight likes to spit an error when I select any of the Dshot protocols, I'm using a DYS f4 v2 flight controller, which is listed as being Dshot600 compatable, and I am using lumenier 30A opto 3-6s BLHeli_s DHSOT ESC's, the only protocol that seems to work is multishot, the esc's are dshot, oneshot, multishot and PWM compatable, yet selecting any dshot, and then saving and reboot results in the errors in the images, I'd be happy to provide logs or more information if you'd like ![image](https://user-images.githubusercontent.com/49452378/274827405-8399082e-2df9-401b-a5c7-bace7ed83625.png) ![image](https://user-images.githubusercontent.com/49452378/274827455-f1e8b750-adf6-48ca-88b6-34958f71b9c3.png)

Your first issue is with Betaflight resource mapping and is not related to the issue in the opening post. Please, can you post this in the Betaflight Discord 'Simple Questions' with the output from:

-  `diff all` 
- `dma show`
-  `timer show` 
and you will get the appropriate assistance:  https://discord.gg/mDtJdc5R

> Please could you read the esc firmware versión is installed in your escs using esc-configurator.com tool? Could you upload a screen capture of your settings?

The resource mapping  needs to be solved first

**Comment by TheRedGamerFPV** [comment]
I've been messing aroud with it for the last hour or so, I've gotten it to work with dshot300, as you said @damosvil it'll just auto set to 300 if I attempt to select dshot600, I'm using the latest version 4.4.2, honestly all I did was flash betaflight to some random version, then I reflashed to 4.4.2, and after loading a backup, it worked as normal, as for what hyp0dermik-code said, I do have one of my motor outputs remapped cause i messed up the solder pad for the motor 2 output, so i just used the motor 6 output, but using multishot would not get that error, the only change I made in betaflight was switching multishot to dshot300, and it gave that error, though now I don't get that error anymore, I'm not sure why any of these errors were even happening in the first place, but everything is working again, I wish I could tell you what fixed it besides I just reflashed betaflight, sorry.

**Comment by stylesuxx** [comment]
Alright, closing this issue since @TheRedGamerFPV's problem is solved and @mankeli is not replying anymore.
