### ISSUE TITLE
EDT safety arm prevents motors activating subsequent to turtle mode,configurator

### ISSUE THREAD

**Issue by hyp0dermik-code** [bird-sanctuary/bluejay#177]
### Describe the issue

EDT safety arm prevents motors activating subsequent to turtle mode, motors tab in BF Configurator in all versions tested down to 4.4.0

In 4.5 master (TBD) the motors tab does not work on first or subsequent attempts

### Bluejay version

.20.1RC2

### ESC variant

A_X_5

### PWM frequency

96

### DShot bitrate

300

### Bidirectional DShot

On

### FC firmware

Betaflight 4.4.0

**Comment by hyp0dermik-code** [comment]
I am not sure if this is intended behaviour or not, or whether it should be if it wasn't

**Comment by damosvil** [comment]
I have reproduced the issue on my side. I will work to fix it.

**Comment by stylesuxx** [comment]
Should we backport this to v0.20.1?

**Comment by damosvil** [comment]
Yes. I tried with v0.20.1. Tomorrow I will start debugging it.

**Comment by damosvil** [comment]
These are the assets for the fix in:
https://github.com/bird-sanctuary/bluejay/pull/178

Please, could you check on your side?
[Bluejay_0.20.1_RC3.zip](https://github.com/bird-sanctuary/bluejay/files/12837165/Bluejay_0.20.1_RC3.zip)
