### ISSUE TITLE
D_X_* & E_X_* Layout

### ISSUE THREAD

**Issue by stylesuxx** [bird-sanctuary/bluejay#207]
* [x] Validate that other targets are not affected
* [x] Validate that new targets are build
* [x] Validate Bluejay D functionality
* [x]  Validate Bluejay E functionality
* [x] Validate BLHeli_S D functionality
* [x] Validate BLHeli_S E functionality
* [x] Validate BLHeli_S D flashing
* [x] Validate BLHeli_S E flashing

**Comment by hyp0dermik-code** [comment]
PR results in no byte difference for A_X target

**Comment by stylesuxx** [comment]
@hyp0dermik-code fyi: in the build dir you have a `compare.sh` script - it will compare two dirs with hex files against each other. Thanks for confirmation.
