### ISSUE TITLE
"Bluejay (.0) version '0.21' (Layout 208) is not yet supported.

### ISSUE THREAD

**Issue by winst0niuss** [bird-sanctuary/bluejay#218]
### Describe the issue

Just flashed my BETAFPV Air75 to bluejay 21 and now i get this error message: 
"Bluejay (.0) version '0.21' (Layout 208) is not yet supported.

When flashing to 0.19.2 - everything is ok

### Bluejay version

0.21.0

### ESC variant

A-X-5

### PWM frequency

96

### DShot bitrate

300

### Bidirectional DShot

On

### FC firmware

Betaflight 4.5.0

### Motor size

0802

### Configurator debug log

[esc-configurator-log.txt](https://github.com/user-attachments/files/17585054/esc-configurator-log.txt)
<img width="1430" alt="screen" src="https://github.com/user-attachments/assets/4c3957b2-8d00-4f4c-abb5-302e515e3022">

**Comment by stylesuxx** [comment]
Configurator version seems wired. Which URL are you flashing from?

**Comment by winst0niuss** [comment]
https://preview.esc-configurator.com/

**Comment by stylesuxx** [comment]
Then please hard refresh the page. Bottom right should show version 0.32.1

**Comment by winst0niuss** [comment]
Sorry, I used the wrong url
On https://esc-configurator.com/ - everything is ok
