### ISSUE TITLE
Port Bluejay to C (?)

### ISSUE THREAD

**Issue by saidinesh5** [bird-sanctuary/bluejay#37]
This is a huge minefield. A good starting point would be to convert keil -> sdcc/sdas8051 and then move to C gradually.

So far, the challenges:
Build system:
* Using platformio - means we have to generate a lot of targets for each of (A-Z layouts) x (L/H/X mcus) x (24/48/96) x (0-120 deadtime). There are ways to do this automatically but it still means we see 1000+ targets in our GUI. Overall, i don't see much value in using platformio for this task compared to good ole' makefiles + sdcc toolchain as a git submodule.
* sdas8051 doesn't seem to offer command line way to define values [1].
* The sdcc version packaged by platform-io seems to be at least [1 version behind sdcc](https://registry.platformio.org/tools/platformio/toolchain-sdcc/compatibility).

Code:
* Keil 's syntax is different from sdas8051 syntax and conventions: [notes on converting keil 8051 to sdcc c](https://hackaday.io/project/170540-adventures-with-a-stc89c52-development-board/log/177065-notes-on-converting-keil-8051-c-to-sdcc-c/) (Some more notes about porting can be learned from [hdzero-vrx repo](https://github.com/hd-zero/hdzero-vtx))
* I did not find tools to automatically convert of keil assembly to sdas8051 (There are existing tools for C)
* Bluejay code uses registers and register banks for variables with our own conventions. So conversion is either all/nothing when it comes to C conversion. SDCC also doesn't seem to support specifying register banks, so [interrupts might still have to be in assembly for more performance](https://sdcc-user.narkive.com/1BwRZ81i/sdcc-register-banks-for-data-storage)

1:
```
$ sdas8051 -h

sdas Assembler V02.00 + NoICE + SDCC mods  (Intel 8051)


Copyright (C) 2012  Alan R. Baldwin
This program comes with ABSOLUTELY NO WARRANTY.

Usage: [-Options] file
Usage: [-Options] outfile file1 [file2 file3 ...]
  -d   Decimal listing
  -q   Octal   listing
  -x   Hex     listing (default)
  -g   Undefined symbols made global
  -n   Don't resolve global assigned value symbols
  -a   All user symbols made global
  -b   Display .define substitutions in listing
  -bb  and display without .define substitutions
  -c   Disable instruction cycle count in listing
  -j   Enable NoICE Debug Symbols
  -y   Enable SDCC  Debug Symbols
  -l   Create list   file/outfile[.lst]
  -o   Create object file/outfile[.rel]
  -s   Create symbol file/outfile[.sym]
  -p   Disable automatic listing pagination
  -u   Disable .list/.nlist processing
  -w   Wide listing format for symbol table
  -z   Disable case sensitivity for symbols
  -f   Flag relocatable references by  `   in listing file
  -ff  Flag relocatable references by mode in listing file
  -I   Add the named directory to the include file
       search path.  This option may be used more than once.
       Directories are searched in the order given.

removing 
```

I will continue updating the issue when there are more findings..

**Comment by hyp0dermik-code** [comment]
Best for a fork or a new project, but some valuable information here.
Noted in the wiki
