### ISSUE TITLE
Preparation of build env fails

### ISSUE THREAD

**Issue by stylesuxx** [bird-sanctuary/bluejay#49]
```
Run rm -rf ~/.wine
http://: Invalid host name.
Error: Process completed with exit code 1.
```
https://github.com/bird-sanctuary/bluejay/actions/runs/3773393953/jobs/6428016523

For some reason the env var with the URL is not being properly set.

**Edit:** Actually that does not seem to be a bug since
> Secrets are not passed to workflows that are triggered by a pull request from a fork.

@saidinesh5 this is a bit of a bummer (obviously it makes sense) and I am wondering if we should simply ditch the password protection on the wine env completely. I would prefer PR's to have builds attached...

**Comment by saidinesh5** [comment]
@stylesuxx https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target we can change the event from pull_request to this .. since we have to approve actions for random triggers, we should be okay with this..?

**Comment by stylesuxx** [comment]
We can try, but I do not think that this will change anything since it is still running on a PR from a fork, which seems to be the main issue here. I will set up a test repo and have a look.

**Comment by stylesuxx** [comment]
@saidinesh5 I looked into it, it seems your suggestion is a good solution. And prevents us from leaking secrets. I am going to implement this.

**Comment by saidinesh5** [comment]
Yeah.. add me to the issue so i can merge it..
