### ISSUE TITLE
Builds failing - again

### ISSUE THREAD

**Issue by stylesuxx** [bird-sanctuary/bluejay#58]
I swear, the workflows are driving me crazy at this point...

```
/usr/bin/docker --config /home/runner/work/_temp/.docker_64a131ba-6387-48ec-b9b1-321b712caa85 login ghcr.io -u damosvil --password-stdin
  /usr/bin/docker --config /home/runner/work/_temp/.docker_64a131ba-6387-48ec-b9b1-321b712caa85 pull ghcr.io/bird-sanctuary/bluejay-builder
  Using default tag: latest
  Error response from daemon: denied
  Warning: Docker pull failed with exit code 1, back off 2.8[17](https://github.com/bird-sanctuary/bluejay/actions/runs/3833271047/jobs/6524550263#step:2:20) seconds before retry.
```

this is then attempted two more times before it fails: https://github.com/bird-sanctuary/bluejay/actions/runs/3833271047/jobs/6524550263

For some reason access is being denied...

@saidinesh5 do you have any idea what the issue could be here? I [checked the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainercredentials) and our setup seems correct (I mean, unsurprisingly, since it has been working fine before). I am not pretty sure this is not a regression introduced by the latest update, since this run still uses the old workflow file. The actor is passed correctly and github_token should be fine too...

**Edit**: I looked a bit more into it - the `GITHUB_TOKEN` permissions are wrong, in the [failed attempts](https://github.com/bird-sanctuary/bluejay/actions/runs/3833271047/jobs/6524944622) it only has this two permissions:
* Contents: read
* Metadata: read

In a past [working attempt](https://github.com/bird-sanctuary/bluejay/actions/runs/3436256540/jobs/5729569853) the token has the following permissions:
-   Actions: write
-   Checks: write
-   Contents: write
-   Deployments: write
-   Discussions: write
-   Issues: write
-   Metadata: read
-   Pages: write
-   PullRequests: write
-   RepositoryProjects: write
-   SecurityEvents: write
-   Statuses: write

I am wondering if the [permissions key](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) now got mandatory?

**Edit 2**: For testing purposes I set the permissions to read-all, this allows my [test PR to build](https://github.com/bird-sanctuary/bluejay/actions/runs/3837975310/jobs/6533891536)...

**Comment by saidinesh5** [comment]
I just changed the github actions permissions of the repository to:

![image](https://user-images.githubusercontent.com/265528/210560536-c02c4516-1a1f-451d-8248-d5bbf41e3309.png)

And everything seems to be working now
