### ISSUE TITLE
Weak turtle mode operation

### ISSUE THREAD

**Issue by damosvil** [bird-sanctuary/bluejay#83]
### Describe the issue

Some users have reported weak turtle mode operation.

### Bluejay version

0.20 rc1

### ESC variant

Any

### PWM frequency

Any

### DShot bitrate

Any

### Bidirectional DShot

Any

### FC firmware

Betaflight  4.4, Silverlight

### Motor size

Any

**Comment by damosvil** [comment]
Looks like that when using dynamic pwm motors don't have enough strength to turn the kwad upside down.

The following patch forces 24khz during user inverted operation (command 21, used in turtle mode). 
https://github.com/bird-sanctuary/bluejay/compare/01b9c6cdcbb877db88113ec837b04624ef645419..b24c462ce5d63daa7c8588a1d1366fb88f2de765

**Comment by stylesuxx** [comment]
But this does not affect 3D mode, right? Because Betaflight has settings to compensate for week turtlemode by spinning the props on the opposite side too...

**Comment by damosvil** [comment]
> But this does not affect 3D mode, right? Because Betaflight has settings to compensate for week turtlemode by spinning the props on the opposite side too...

I think it doesn't. This bug is related to the blown fets.

**Comment by damosvil** [comment]
It worked fine in Tested in the Meteor 65

**Comment by KondratokGK** [comment]
Turtle mode not working. It`s wrong motor rotation for turtle mode. It spins as normal mode.

**Comment by stylesuxx** [comment]
@KondratokGK please provide more info, this statement helps in no way to debug anything.

Which RC of 0.20.0 are you on exactly? Which flight controller firmware are you using? Which version of FC version? Which ESCs are you using (Layout and dead-time).

**Comment by damosvil** [comment]
Scope has been reduced for 0.20
