### ISSUE TITLE
Release Notes v0.20.0

### ISSUE THREAD

**Issue by stylesuxx** [bird-sanctuary/bluejay#84]
This time so many things happened, I would like to add some more details to the release instead of just the summary of the PRs.

## Quality of life improvements
* Massive code refactoring, everything has been refactored into smaller, more readable modules:
  * #99
  * #103
  * #104
  * #107
  * #116
  * #117
  * #119
  * #128
* Auto formatting has been applied and preparations have been made to check for proper formatting in PRs:
  * #93

## Safety features
* **EDT safety arm** ensures that the ESC will only arm after a valid EDT handshake. This will only work with flight controller firmware that support EDT functionality.
* Temp protection is **disabled** by default: Since temp protection has effectively not been working for a long time (probably ever), the default is no to be disabled to prevent users from running into issues where they are "losing power". If temp protection is enabled, make sure that the "power rating" setting is set correctly and best verify via EDT and temperature readout on Betaflight, that the Temperature values are in a sane range (around 50): 
  * #95

## Bugfixes 
* 3D mode is now back to working again after we broke it in 0.17.x:
  * #105
  * #138
* Reduced frequency of operation of EDT and temperature protection scheduler:
  * #102

## Misc
* Since the current dithering implementation does not do what it is promising to do, we opted to disable it per default for the time being (more info in the following section). (#130)
* New layouts have been added. We were running out of letters for new ESC layouts and thought we might just make it if no new layouts pop up, but this of course is not the case - so we future proofed this and added functionality for ESC layouts to have 2 characters instead of one:
  * #113
* Add supporter section:
  * #85
  * #89
  * #139

## Findings
A lot of the planned features for 0.20 needed to be postponed to a later release since they are not working in a satisfactory way:
* Dynamic and variable PWM has been somewhat successful but not fully satisfactory to us. It is wasting a lot of CPU cycles, CPU cycles we do not have
* The current dithering implementation is eating up a lot of CPU cycles and is a bit flawed since it is only applied to every DSHOT package instead of every PWM cycle. Testing has shown that there is little to no difference in having vs. not having dithering in the current implementation. We might in the future ditch dithering in favor of gaining some CPU cycles to get some other - for us - more important features implemented
* In process of experimenting with dynamic PWM we came to the conclusion that 96kHz mode is pretty much useless and we might get rid of it in the future. The resolution on 96kHz is 256 steps in the best case. Considering deadtime, (which needs to be subtracted) - having high dead times reduces this even further. 

# OLD Draft for 0.20 - will probably be part of 0.21 and later versions

## PWM baked in
PWM is now a setting that can be changed on the fly, no re-flashing of the ESCs is required anymore. Users can chose between 24kHz (Default), 48kHz, 96kHz and dynamic PWM.

## Dynamic PWM
PWM is being changed dynamically during flight. Thresholds can be set by the user via configurator. PWM is being change between 24kHz, 48kHz and 96kHz

## Min/Max startup power
Min/Max startup power needs to be adjusted in such a way, that the motors start spinning when armed. On smaller quads this means you will likely have to increase the values, on bigger ones, decrease. Be aware that the correct values  are highly depended on the dead time of your ESCs and the selected PWM.

## Improved commutation
Commutation has been improved massively, resulting in motors that run much cleaner - you can even hear it. Additionally with EDT this now allows to log the "stress" of a motor in flight.

## Improved stall protection
The ESCs are now more capable than ever to detect stalls and act accordingly, this ensures less motor and ESC damage in situations where the motor would be blocke from spinning up, for example after a crash.

## Safety features
**EDT safety arm** ensures that the ESC will only arm after a valid EDT handshake. This will only work with flight controller firmware that support EDT functionality.

## Bugfixes 
* 3D mode is now back to working again after we broke it in 0.17.x
* Timer 3 now uses it's own overflow bit to track for timer overflows instead of checking this manually

## Quality of life improvements
* Massive code refactoring, everything has been refactored into smaller, more readable modules

## Postponed
The following features have first apperared in 0.20.0 but have been postponed to a later version for one reason or another

**RC filtering/smoothing**. As a fallback for bad tunes RC signal filtering has been implemented, this ensures that quick changes in RC signal extremes are smoothed out, prevents motors getting hot and ultimately frying. If you are not using highly experimental tunes the recommendation is to leave filters disabled as it might interfere with what you are expecting from your tune.

**Comment by rohansx** [comment]
hey, would love to contribute to this. Assign me.

**Comment by stylesuxx** [comment]
@rohansx huh? You want to write the release notes? Sure, feel free to add your comment...

**Comment by damosvil** [comment]
In Dynamic PWM section:
PWM is __**not**__ a setting -> PWM is __**now**__ a setting?
