### ISSUE TITLE
Increase min/max startup power

### ISSUE THREAD

**Issue by stylesuxx** [bird-sanctuary/bluejay#88]
Some builds, especially with bigger motors and smaller batteries might benefit from an increases min/max startup power range.

**Comment by stylesuxx** [comment]
This needs re-evaluation.

@hyp0dermik-code What's your opinion on this, you think it would make sense to increase the range. I am not sure if this is necessary any longer...

**Comment by hyp0dermik-code** [comment]
Personally I have never seen a case where this was necessary or even close to, especially with the clarification around motor idle and startup power
